###########
# site.title, site.url, site.author.name
title: 'Wiki theme documentation'
author:
  name: 'Balogh Zolt치n S치ndor'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 'http://watvr.me'
url: 'http://watvr.me/home'

# Site Settings (this can be reaced in code with site.settings.PROPERTY_PLACEHOLDER)
settings: {
  # Basic section
  home: "/docs",
  redirectTimeOut: 10,
  private: false,
  # END #

  # Header section
  hasHeader: true,
  # END #

  # Contact section
  contactUs: { ownerName: "Balogh Zolt치n S치ndor",supportEmail: "zoltan.balogh@avolantis.net" },
  # END #

  # Developer Tools Section
  devTool: {
    key: cabata
  }
}

markdown: kramdown

sass:
  sass_dir: css
  style: expanded

permalink: /:title.html

exclude:
  - README.md

safe: true
lsi: false
